#!/usr/bin/env python3
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "overtun-lib",
# ]
#
# [tool.uv.sources]
# overtun-lib = { path = "." }
# ///
import overtun.scripts


if __name__ == "__main__":
    overtun.scripts.main()
